### ISSUE TITLE
[JOSS Review] Any citations using this method or demonstrating its need?

### ISSUE THREAD

**Issue by billbrod** [elliohow/fMRI_ROI_Analysis_Tool#37]
Are there any citations that could be included in the JOSS paper that use ROI-level analysis, discuss it, or demonstrate the need / utility of it (e.g., showing problems with voxelwise methods)? 

https://github.com/openjournals/joss-reviews/issues/5200

**Comment by elliohow** [comment]
Functionally derived ROIs can be problematic in many circumstances as this can result in a circular assessment of the data (www.ncbi.nlm.nih.gov/pubmed/20571517), as described by Geuter et al. 2018 (https://www.biorxiv.org/content/10.1101/295048v1.full). Instead it is often preferable to use  atlas derived ROIs based on anatomy, previous literature, or a separate localizer scan when a strong a priori hypothesis exists. We have now modified the manuscript to make this point.

**Comment by billbrod** [comment]
Excellent. And it looks like this is included at the end of the [statement of need](https://fmri-roi-analysis-tool.readthedocs.io/en/latest/statement_of_need.html), right? I'd highlight it more: circularity and inflated effect size is a big problem of fMRI, so I'd really underline the importance of avoiding this -- pull the related text out of that last paragraph, maybe make it its own section. Right now, it sounds like an afterthought, because it's halfway through the last paragraph, which starts with "an example use-case". What do you think?

**Comment by elliohow** [comment]
Yes that makes sense. I will highlight it more in the documentation's statement of need. Is it ok as it currently is in the paper?

**Comment by billbrod** [comment]
Yup! Once you make those changes in the docs version, I'll close this issue.

**Comment by elliohow** [comment]
I've updated the statement of need page of the documentation.
