### ISSUE TITLE
[JOSS Review] Community guidelines

### ISSUE THREAD

**Issue by billbrod** [elliohow/fMRI_ROI_Analysis_Tool#39]
Instructions for opening an issue or getting help are present, but there's nothing for how to contribute. I would like to see a code of conduct and contributing guide. Here's a template from [the Turing Way](https://github.com/alan-turing-institute/reproducible-project-template), and some examples: [matplotlib](https://matplotlib.org/stable/devel/contributing.html#contributing), [nipype](https://github.com/nipy/nipype/blob/master/CONTRIBUTING.md)

https://github.com/openjournals/joss-reviews/issues/5200

**Comment by billbrod** [comment]
It's not necessary, but the discussion in #35 reminded me: it might be useful to define a bug report [issue template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) that will prompt users for a  lot of the basic information: what fRAT version, what FSL version, what python version, attach a screenshot or pasted version of the terminal output ,etc.

**Comment by billbrod** [comment]
I think that's a good start, but I think a code of conduct (you can lightly adapt [this one](https://www.contributor-covenant.org/)) is necessary. 

And, while not necessary, the following would be nice to add to the contributing section: what kind of contributions you're interested and uninterested in (more documentation, examples, new features, integration with other tools, etc.), any info about coding style or API, and required documentation and/or tests. Basically, what should they include in the PR? E.g., a description of what it includes, a small working example, the need it fills, etc.

**Comment by billbrod** [comment]
Some guidance on [codes of conduct](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/) and [contributor guidelines](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-contributor-guidelines/) from Mozilla's open leadership program.

**Comment by elliohow** [comment]
I've added a code of conduct, contributing guidelines and issue templates, and linked to them in the documentation.

**Comment by billbrod** [comment]
This looks good!
