### ISSUE TITLE
[JOSS REVIEW] Documentation for “critical parameters” 

### ISSUE THREAD

**Issue by ZeitgeberH** [elliohow/fMRI_ROI_Analysis_Tool#42]
In the `Parsing` phase, default `critical parameters` are `Multiband` and `SENSE`.
Are there any other parameters currently supported. If yes,  could you put that in the documentation anywhere. If not, please add a few words about that in documentation.
The tooltips actually contain very useful information.  I suggest you copy these text (at least for the critical parameters part) into your documentation as well.

**Comment by elliohow** [comment]
Yes, any parameter is supported. I've updated the tutorial with the below text to reflect this:

> The critical parameter settings are used to supply the names and file name abbreviations of the independent variables, therefore `fRAT` supports the use of any parameters (and any number of them).
> 
> If `critical parameters` is left blank, the ROI analysis will combine all datasets, regardless of the independent
> variable used for each file. This can be useful for calculating tSNR across the entire dataset, if the independent
> variable does not affect tSNR.
> 
> It is also possible to only supply one critical parameter. For example, if `critical parameters` was set to
> "Coffee cups drank" and `critical parameters abbreviation` was set to "cf". For the filename ``cf1.nii``, for
> the independent variable "Coffee cups drank" the condition would be set to 1. It would then be possible to get a
> summary of t-statistic maps by ROI for each condition. To do this, you would need to calculate 
> t-statistic maps for each condition prior to running the ROI analysis, and place the maps in each participant's 
> statmap folder.

I've also updated the tooltip with version `1.3.5`.
