### ISSUE TITLE
[JOSS REVIEW] Bolded font and ROI specification missing

### ISSUE THREAD

**Issue by ZeitgeberH** [elliohow/fMRI_ROI_Analysis_Tool#43]
This is maybe another OS specific thing.
In the documentation for [Running the ROI analysis](https://fmri-roi-analysis-tool.readthedocs.io/en/latest/tutorials/Basic-ROI-analysis.html#id5), you mentioned "Again, the default options should be sufficient, however the **bolded** options are the ones most likely to need changing. ". 
I did not see any bolded part either in the `General` panel or the `Home` Panel

For the `Atlas information`, you mentioned " This allows you to both select which atlas is more appropriate to use for analysis, but also allows you to specify using this numeric tags which ROIs to produce figures and statistics for, e.g. 1,5,32 to choose specific ROIs or all for all ROIs". I did not find a place where i can specify ROIs. Is it only supported in scripting rather than GUI. Or you are refering the `Atlas` in the `Analysis` panel (the dropdown menu which allows user to select atlas there)

![general](https://user-images.githubusercontent.com/7234420/228956548-832f6f11-ceb6-45d3-bff2-1c3afe2a1ddf.PNG)

**Comment by elliohow** [comment]
> This is maybe another OS specific thing. In the documentation for [Running the ROI analysis](https://fmri-roi-analysis-tool.readthedocs.io/en/latest/tutorials/Basic-ROI-analysis.html#id5), you mentioned "Again, the default options should be sufficient, however the **bolded** options are the ones most likely to need changing. ". I did not see any bolded part either in the `General` panel or the `Home` Panel

Yes this is an OS specific issue. MacOS and Ubuntu 18.04 both display bolded fonts correctly, although the font size is much larger in the GUI on Ubuntu compared to MacOS. Making the GUI 100% consistent across OSs might be for a future version as it is an aesthetic issue, however using bold text to represent key parameters is definitely something that could improve the UX  and is something I think should be present across all OSs if possible. Which version of linux in WSL2 are you running?

> For the Atlas information, you mentioned " This allows you to both select which atlas is more appropriate to use for analysis, but also allows you to specify using this numeric tags which ROIs to produce figures and statistics for, e.g. 1,5,32 to choose specific ROIs or all for all ROIs". I did not find a place where i can specify ROIs. Is it only supported in scripting rather than GUI. Or you are refering the Atlas in the Analysis panel (the dropdown menu which allows user to select atlas there)

The intention was to use the terminal printout of the "atlas information" to select which atlas to use for analysis (using the dropdown menu in the Atlas option of the Analysis page), but also to see which ROIs are most relevant for you. The numbers corresponding to the relevant ROIs can then be used in the "ROIs to calculate statistics for" and "ROIs to plot" options (in the statistics and plotting menus respectively) to be more selective in ROI choice. I can see its very unclear where ROI and atlas choice should actually made though so will change this.

Regarding scripting, as the complexity of `fRAT` increased and the ability to combine data between participants was added, it became less necessary (and more difficult) to run multiple datasets through the analysis pipeline with different settings. So the ability to script was taken out a while ago in favour of using the GUI. This ability may be added in the future, however the complexity of manually changing configuration settings and making sure they are in the correct toml format may make scripting  `fRAT` prohibitively difficult for most users, so may not be worth adding.

**Comment by ZeitgeberH** [comment]
> however using bold text to represent key parameters is definitely something that could improve the UX and is something I think should be present across all OSs if possible

Sounds good!



> Which version of linux in WSL2 are you running?
22.04 LTS

**Comment by elliohow** [comment]
I've updated the documentation describing the atlas information to increase clarity, i've also hopefully fixed the bold text issue with version `1.3.5`. Let me know if this version fixes the text issue for you 😃

**Comment by ZeitgeberH** [comment]
I can see the documentation has been largely improved! 👍 
Unfortunately,  `1.3.5` did not fix the bold text in my end. This seems to be an issue for Tkinter's font library not recognized by Python in Linux system. see [here](https://stackoverflow.com/questions/47769187/make-anacondas-tkinter-aware-of-system-fonts-or-install-new-fonts-for-anaconda).
For now,  I don't think this is a issue,  as long as the documentation has good explanation for the parameters that users should pay more attention.

**Comment by ZeitgeberH** [comment]
For the record, i found one solution for this, based on [this thread](https://github.com/ContinuumIO/anaconda-issues/issues/6833)

In short, I installed fRAT in a conda environment which has a problem with `tk`, a solution of this is to remove conda's `tk` (`conda remove --force tk` ) and force Python use system's `tk`.
The default size for the heading would be too large, I dialed down down to 

```
self.heading_font.configure(weight='bold', size=15)
self.subheading_font.configure(weight='bold', size=12)
```



![Capture](https://user-images.githubusercontent.com/7234420/229617853-6137ee39-b689-4651-9ad0-000e6ca6f163.PNG)
