### ISSUE TITLE
[JOSS REVIEW] Folder selection

### ISSUE THREAD

**Issue by ZeitgeberH** [elliohow/fMRI_ROI_Analysis_Tool#44]
### Summary
Hi,
I went through the [Running the ROI analysis](https://fmri-roi-analysis-tool.readthedocs.io/en/latest/tutorials/Basic-ROI-analysis.html#running-the-roi-analysis) part. 
The output folder is missing several subfolders  mentioned in that section (see screen shot): `Figures`, `fRAT_report`,  `Statistics` 

I noticed the terminal output stating that the `statmaps` was not specified. This may be the cause of it, although i did the run the `statmap` part without problem.  I think i may miss-specified the outfolder in the analysis process. `fRAT`  ask three or four times for output directory.  This may cause confusion and mishaps. I think your way to run the `test-suit` was very smooth.  Is it possible to ask user to specify root folder for a project only at the beginning and let `fRAT` to handle all the subfolders path.  I think that is one of the strength of `fRAT`,  scaffolding project folders to automatically organize multiple data sources and analysis results. 

### Platform details:
 - OS:  Ubuntu 22.04 on WSL2
 - Python version: 3.10.
 - fRAT version: 1.3.5
 - FSL version: 6.0.6
 - Package managers used (other than pip and pipx): Conda

![Capture](https://user-images.githubusercontent.com/7234420/232615940-65b2f0b0-46a7-4ef9-aa43-30b7575fbe5b.PNG)

**Comment by elliohow** [comment]
Hi, please can you paste the analysis_log.toml file here and I can take a look

**Comment by elliohow** [comment]
You can turn off the analysis option now since it has already been ran, the analysis output folder should be selected now though instead of the root folder. Not sure if that is clear from the documentation

**Comment by ZeitgeberH** [comment]
That's good feature! Reuse the analysis to twist the plotting and reporting part. Definitely worth to highlight in your doc. I may missed that part of doc. 


----

With `analysis` off, it gives me a `FileNotFoundError`
`FileNotFoundError: File /home/mlk/Documents/fRAT/testData/Overall/Summarised_results/Participant_averaged_results/combined_results.json does not exist`.

I check the `combined_results.json` file, it does exist in that directories.  I figure out it was due to that I pointed the saving folder to the root folder.

Pointing it to the output folder `HarvardOxford-Cortical_ROI_report` works. 

---------------------

The analysis was killed at the step of `Saving Participants table`
```
Saving Participants table.
Killed
(frat310) mlk@MingPC:~$ /home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/multiprocess/resource_tracker.py:227: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

Not sure what's the cause. I noticed it requires a large RAM to run this step (~20G for your example data; my desktop has 64 G RAM).

**Comment by elliohow** [comment]
It may be worth reducing the max core usage to 6 as I see it is currently set to max. If that solves the issue I'll add a hard cap into `fRAT` to disallow usage of more than 6 cores at a time to reduce RAM usage. How many cores and threads does your computer have?

**Comment by ZeitgeberH** [comment]
> It may be worth reducing the max core usage to 6 as I see it is currently set to max. If that solves the issue I'll add a hard cap into `fRAT` to disallow usage of more than 6 cores at a time to reduce RAM usage. How many cores and threads does your computer have?

24

**Comment by ZeitgeberH** [comment]
There's type error for function `start_processing_pool` at line 323 in `utils.py`
you may want to warp it `workers = config.max_core_usage` 
with 
`workers = int (config.max_core_usage)`

**Comment by ZeitgeberH** [comment]
Similar error for 6 workers. 

```
Saving Participants table.
Maximum ROI value of: 2 seen for parameter combination: mb4_s1.5. Creating figures with this colourbar limit.
Saving Participants_same_scale table.
Killed
```

**Comment by ZeitgeberH** [comment]
Same error for 3 workers.

**Comment by ZeitgeberH** [comment]
Tried with `Multicore processing` off, still the same problem. 
The verbose mode gave out some warnings (see below).  You could try to close those saved figures. Maybe that is the culprit. 


```
Saving Sessions table.
/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/fRAT/utils/figures.py:270: ResourceWarning: unclosed file <_io.BufferedReader name='mb4_s1.5_Sessions.png'>
/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/fRAT/utils/figures.py:270: ResourceWarning: unclosed file <_io.BufferedReader name='mb1_s2.0_Sessions.png'>
/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/fRAT/utils/figures.py:270: ResourceWarning: unclosed file <_io.BufferedReader name='mb1_s1.5_Sessions.png'>
/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/fRAT/utils/figures.py:270: ResourceWarning: unclosed file <_io.BufferedReader name='mb3_s1.5_Sessions.png'>
/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/fRAT/utils/figures.py:270: ResourceWarning: unclosed file <_io.BufferedReader name='mb3_s2.0_Sessions.png'>
Killed
```

**Comment by elliohow** [comment]
> I noticed the terminal output stating that the `statmaps` was not specified. This may be the cause of it, although i did the run the `statmap` part without problem.

This message occurs to warn that a log of the stamap folder used wont be saved. If there is one statmap folder for each participant and statmap folder to use has not been specified, it will default to using that folder and show that warning. If statmap has not been specified and there are multiple statmap folders, the program will exit with an error.

> I think i may miss-specified the outfolder in the analysis process. `fRAT` ask three or four times for output directory. This may cause confusion and mishaps. I think your way to run the `test-suit` was very smooth. Is it possible to ask user to specify root folder for a project only at the beginning and let `fRAT` to handle all the subfolders path. I think that is one of the strength of `fRAT`, scaffolding project folders to automatically organize multiple data sources and analysis results.

Currently the user can set the locations for the root and report output folders in the GUI. If paths have been given for these settings, the file explorer won't pop up. Although it would also be useful to have the root, statmap and output folders be saved for the current session once those steps have been ran, so i've added this to my list of future additions.

**Comment by ZeitgeberH** [comment]
Sounds good.  After upgrading to version `1.3.6` ,  I still got the same error without multicore processing. 
I am closing this issue now, as this may not be a problem for other platform as you observed in your OS.

**Comment by elliohow** [comment]
Took a while to debug this one. Looks like its a known issue with Matplotlib not being able to clean up plots properly when creating them in a loop, causing a memory leak. Its popped up quite a few times in their issues: #https://github.com/matplotlib/matplotlib/issues/20490

Changing the Matplotlib backend to a non-GUI backend fixed this:
```
import matplotlib
matplotlib.use('Agg')
```

I'm not sure why it isn't causing issues on Mac, it may be a difference in how Tk handles Matplotlib GUI elements between the two OSs, but i've also seen people report it as an issue when using a Jupyter notebook. `1.3.7` should fix this. Tagging @billbrod in case you also run into this issue
